### ISSUE TITLE
Joining measurements does not work

### ISSUE THREAD

**Issue by ArtificialBlackSheep** [ZELLMECHANIK-DRESDEN/DCKit#20]
When joining two measurements with DCKIT 0.12.16 I get the following error:

Unhandled exception in DCKit version 0.12.16:
Traceback (most recent call last):
  File "dckit\main.py", line 435, in on_task_join
    dclab.cli.join(path_out=po,
  File "dclab\cli\task_join.py", line 89, in join
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\_hl\group.py", line 305, in __getitem__
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'index_online' doesn't exist)"

With the previous version 0.12.12 it worked fine.

**Comment by paulmueller** [comment]
The problem that you have here is that one of the files you are joining contains the feature `index_online` and the other file does not. The old version of DCKit did not check for that and thus created an `index_online` feature that is incomplete (as far as I can see from looking at the code).

I think the best way to go about this is to just drop all features that are not contained in all datasets and issue a warning (which will be written to the logs in DCKit).

This can be resolved in dclab. I have created an issue there.
TODO:

- [ ] https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/157
- [ ] bump version of dclab after that

**Comment by paulmueller** [comment]
I have to correct myself. This is the actual issue: https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/158
But I am going to implement dclab#157 anyway.
